apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: danielmtz-website-dev
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
images:
  - name: ghcr.io/danielmtzbarba/danielmtz-website
    newTag: 8ca6df9210cf6aa385068ebe8fcf1e7e80db2f81
