apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: danielmtz-website-dev
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
images:
  - name: ghcr.io/danielmtzbarba/danielmtz-website
    newTag: 1531e10bbd2152e3940ea8f1014b54b921b05d73
