apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: danielmtz-website-dev
resources:
  - namespace.yaml
  - ghcr-pull-secret-externalsecret.yaml
  - deployment.yaml
  - service.yaml
images:
  - name: ghcr.io/danielmtzbarba/danielmtz-website
    newTag: dev-4dec1b2176d3b176584e670b762d71724df8a74d
