apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alertmanager-slack-webhook
  namespace: observability
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secret-manager
  target:
    name: alertmanager-slack-webhook
    creationPolicy: Owner
  data:
    - secretKey: url
      remoteRef:
        key: k3s-alertmanager-slack-webhook-url
