alertmanager:
  enabled: false

grafana:
  defaultDashboardsTimezone: utc
  service:
    type: ClusterIP
  persistence:
    enabled: false
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  additionalDataSources:
    - name: Loki
      type: loki
      access: proxy
      url: http://loki-gateway.observability.svc.cluster.local
      isDefault: false
      jsonData:
        maxLines: 1000

kubeControllerManager:
  enabled: false

kubeEtcd:
  enabled: false

kubeScheduler:
  enabled: false

prometheus:
  service:
    type: ClusterIP
  prometheusSpec:
    retention: 7d
    retentionSize: 15GB
    resources:
      requests:
        cpu: 300m
        memory: 1Gi
      limits:
        cpu: "1"
        memory: 2Gi
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 20Gi

prometheus-node-exporter:
  enabled: true
