apiVersion: v1
kind: Service
metadata:
  name: execution-vm
  namespace: quant-engine-mt5
  labels:
    app.kubernetes.io/part-of: quant-engine
    environment: dev
    app.kubernetes.io/component: legacy-bridge
spec:
  ports:
    - name: mt5-api
      port: 8000
      targetPort: 8000
    - name: sync-api
      port: 8080
      targetPort: 8080
