apiVersion: v1
kind: Endpoints
metadata:
  name: execution-vm
  namespace: quant-engine-mt5
subsets:
  - addresses:
      - ip: 10.10.0.20
    ports:
      - name: mt5-api
        port: 8000
        protocol: TCP
      - name: sync-api
        port: 8080
        protocol: TCP
