apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: quant-engine-mt5
resources:
  - core-configmap.yaml
  - core-externalsecret.yaml
  - core-deployment.yaml
  - core-service.yaml
  - core-servicemonitor.yaml
  - messaging-configmap.yaml
  - messaging-externalsecret.yaml
  - messaging-deployment.yaml
  - messaging-service.yaml
  - messaging-servicemonitor.yaml
  - messaging-ingress.yaml
  - sync-configmap.yaml
  - sync-externalsecret.yaml
  - sync-deployment.yaml
  - sync-service.yaml
  - sync-servicemonitor.yaml
images:
  - name: ghcr.io/danielmtzbarba/core_service
    newTag: dev-dc277339e48cab43f0e96b0487434e3dbf33533b
  - name: ghcr.io/danielmtzbarba/messaging_service
    newTag: dev-dc277339e48cab43f0e96b0487434e3dbf33533b
  - name: ghcr.io/danielmtzbarba/sync_service
    newTag: dev-dc277339e48cab43f0e96b0487434e3dbf33533b
