apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: quant-engine-mt5
resources:
  - core-configmap.yaml
  - core-externalsecret.yaml
  - core-deployment.yaml
  - core-service.yaml
  - core-servicemonitor.yaml
  - messaging-configmap.yaml
  - messaging-externalsecret.yaml
  - messaging-deployment.yaml
  - messaging-service.yaml
  - messaging-servicemonitor.yaml
images:
  - name: ghcr.io/danielmtzbarba/core_service
    newTag: 1741afff0ace1a0a08fa73bc7e368642954a23ba
  - name: ghcr.io/danielmtzbarba/messaging_service
    newTag: 1741afff0ace1a0a08fa73bc7e368642954a23ba
