apiVersion: v1
kind: Service
metadata:
  name: quant-engine-dev-sync-service
  namespace: quant-engine-mt5
  labels:
    app.kubernetes.io/name: quant-engine-dev-sync
    app.kubernetes.io/part-of: quant-engine
    environment: dev
spec:
  selector:
    app.kubernetes.io/name: quant-engine-dev-sync
  ports:
    - name: http
      port: 8080
      targetPort: http
