apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability-promtail
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: observability
spec:
  project: default
  source:
    repoURL: git@github.com:danielmtzbarba/k3s-homelab.git
    targetRevision: main
    path: kubernetes/platform/promtail
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
