apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: quant-engine-prod
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: quant-engine
    environment: prod
spec:
  project: default
  source:
    repoURL: git@github.com:danielmtzbarba/k3s-homelab.git
    targetRevision: main
    path: kubernetes/apps/quant-engine-prod
  destination:
    server: https://kubernetes.default.svc
    namespace: quant-engine-mt5
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
