apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: quant-engine-mt5
resources:
  - namespace.yaml
  - ghcr-pull-secret-externalsecret.yaml
  - influxdb-externalsecret.yaml
  - influxdb-service.yaml
  - influxdb-statefulset.yaml
  - mt5-configmap.yaml
  - mt5-externalsecret.yaml
  - mt5-runtime-service.yaml
  - mt5-servicemonitor.yaml
  - mt5-deployment.yaml
images:
  - name: ghcr.io/danielmtzbarba/mt5_service
    newTag: dev-b200c90f05b2db49eccc8f9fd03c8a4e0fedc83e
