apiVersion: v1
kind: Endpoints
metadata:
  name: quant-engine-sync
  namespace: quant-engine-mt5
subsets:
  - addresses:
      - ip: 10.10.0.20
    ports:
      - name: sync-api
        port: 8080
        protocol: TCP
