apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ghcr-pull-secret
  namespace: danielmtz-website-prod
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secret-manager
  target:
    name: ghcr-pull-secret
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
  data:
    - secretKey: .dockerconfigjson
      remoteRef:
        key: k3s-website-prod-ghcr-pull-secret
