apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: quant-engine-dev-updater
  namespace: argocd
spec:
  applicationRefs:
    - namePattern: "quant-engine-dev"
      images:
        - alias: "core"
          imageName: "ghcr.io/danielmtzbarba/core_service"
          commonUpdateSettings:
            updateStrategy: "newest-build"
            allowTags: "regexp:^dev-[0-9a-f]{40}$"
            pullSecret: "pullsecret:argocd/ghcr-pull-secret"
        - alias: "messaging"
          imageName: "ghcr.io/danielmtzbarba/messaging_service"
          commonUpdateSettings:
            updateStrategy: "newest-build"
            allowTags: "regexp:^dev-[0-9a-f]{40}$"
            pullSecret: "pullsecret:argocd/ghcr-pull-secret"
        - alias: "sync"
          imageName: "ghcr.io/danielmtzbarba/sync_service"
          commonUpdateSettings:
            updateStrategy: "newest-build"
            allowTags: "regexp:^dev-[0-9a-f]{40}$"
            pullSecret: "pullsecret:argocd/ghcr-pull-secret"
      writeBackConfig:
        method: "git:secret:argocd/k3s-homelab-writeback"
        gitConfig:
          repository: "https://github.com/danielmtzbarba/k3s-homelab.git"
          branch: "main"
          writeBackTarget: "kustomization:/kubernetes/apps/quant-engine-dev"
