apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: quant-engine-prod-core-secrets
  namespace: quant-engine-mt5
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secret-manager
  target:
    name: quant-engine-prod-core-secrets
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: k3s-quant-engine-prod-core-env
