apiVersion: v1
kind: Service
metadata:
  name: quant-engine-prod-core-service
  namespace: quant-engine-mt5
  labels:
    app.kubernetes.io/name: quant-engine-prod-core
    app.kubernetes.io/part-of: quant-engine
    environment: prod
spec:
  selector:
    app.kubernetes.io/name: quant-engine-prod-core
  ports:
    - name: http
      port: 8001
      targetPort: http
