apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: quant-engine-prod-messaging
  namespace: quant-engine-mt5
  labels:
    release: kube-prometheus-stack
    app.kubernetes.io/part-of: quant-engine
    environment: prod
spec:
  namespaceSelector:
    matchNames:
      - quant-engine-mt5
  selector:
    matchLabels:
      app.kubernetes.io/name: quant-engine-prod-messaging
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
