apiVersion: v1
kind: ConfigMap
metadata:
  name: quant-engine-prod-messaging-config
  namespace: quant-engine-mt5
data:
  MSG_CORE_SERVICE_URL: http://quant-engine-prod-core-service:8001
  MSG_SYNC_SERVICE_URL: http://quant-engine-prod-sync-service:8080
  MSG_MT5_SERVICE_URL: http://quant-engine-mt5-service:8000
  MSG_APP_URL: https://replace-prod-app-url.example.com
