apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: repo-k3s-homelab
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secret-manager
  target:
    name: repo-k3s-homelab
    creationPolicy: Owner
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository
      data:
        type: git
        url: git@github.com:danielmtzbarba/k3s-homelab.git
        sshPrivateKey: "{{ .sshPrivateKey }}"
  data:
    - secretKey: sshPrivateKey
      remoteRef:
        key: k3s-argocd-repo-ssh-private-key
