apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: gcp-secret-manager
spec:
  provider:
    gcpsm:
      projectID: your-gcp-project-id
      auth:
        secretRef:
          secretAccessKeySecretRef:
            name: gcpsm-secret
            namespace: external-secrets
            key: secret-access-credentials
