apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: gcp-secret-manager
spec:
  provider:
    gcpsm:
      projectID: k3s-homelab-danielmtz
      auth:
        workloadIdentityFederation:
          audience: //iam.googleapis.com/projects/727653609299/locations/global/workloadIdentityPools/k3s-homelab/providers/k3s-server-1
          serviceAccountRef:
            name: eso-gcpsm
            namespace: external-secrets
            audiences:
              - //iam.googleapis.com/projects/727653609299/locations/global/workloadIdentityPools/k3s-homelab/providers/k3s-server-1

