apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: gcp-secret-manager
spec:
  provider:
    gcpsm:
      projectID: k3s-homelab-danielmtz
      auth:
        secretRef:
          secretAccessKeySecretRef:
            name: gcpsm-secret
            namespace: external-secrets
            key: secret-access-credentials
