apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: quant-sync-private
  namespace: quant-engine-mt5
  annotations:
    tailscale.com/tags: "tag:k8s"
spec:
  ingressClassName: tailscale
  tls:
    - hosts:
        - quant-sync
  rules:
    - host: quant-sync
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: quant-engine-dev-sync-service
                port:
                  number: 8080
